name: Build and Deploy to GitHub Pages

on:
  push:

env:
  node_version: 23.x

jobs:
  build:
    name: Build Example App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build React app
        run: |
          cd examples/web-auth-example
          yarn install --immutable
          yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: example-app-build
          path: examples/web-auth-example/dist
          retention-days: 1

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: example-app-build
          path: examples/web-auth-example/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: examples/web-auth-example/dist
